# Generated by Django 4.2 on 2023-04-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="study_board",
            name="writer",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
