# Generated by Django 4.2 on 2023-04-28 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("study_board", "0002_study_board_writer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.RemoveField(
            model_name="study_board",
            name="writer",
        ),
        migrations.AddField(
            model_name="study_board",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
